# Generated by Django 4.2.5 on 2023-10-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('prenom', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('description', models.TextField()),
                ('imageName', models.ImageField(upload_to='Acteurs')),
            ],
        ),
    ]
