# Generated by Django 4.2.5 on 2023-10-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Realisateur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realisateur',
            name='imageName',
            field=models.ImageField(default=0, upload_to='Realisateurs'),
            preserve_default=False,
        ),
    ]
