# Generated by Django 4.2.5 on 2023-10-03 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Films', '0003_remove_films_schedule_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('created_date', models.DateField()),
                ('imageName', models.CharField(max_length=250)),
                ('realisateur_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='Films.realisateur')),
            ],
        ),
    ]
