# Generated by Django 4.2.5 on 2023-10-02 16:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=250)),
                ('nom', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('created_date', models.DateField()),
                ('imageName', models.CharField(max_length=250)),
                ('schedule_date', models.DateField(default=datetime.datetime(2023, 10, 9, 18, 56, 59, 962697))),
                ('realisateur_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='films', to='Films.realisateur')),
            ],
        ),
    ]
