# Generated by Django 4.2.5 on 2023-10-02 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Films', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='schedule_date',
            field=models.DateField(default=datetime.datetime(2023, 10, 9, 18, 57, 19, 211294)),
        ),
    ]
