# Generated by Django 4.2.5 on 2023-10-02 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Films', '0002_alter_films_schedule_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='films',
            name='schedule_date',
        ),
    ]
