# Generated by Django 4.2.5 on 2023-10-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Films', '0003_remove_films_schedule_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='duree',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
