# Generated by Django 4.2.5 on 2023-10-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Films', '0004_films_duree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='imageName',
            field=models.FileField(max_length=250, upload_to=''),
        ),
    ]
