# Generated by Django 4.2.5 on 2023-10-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Films', '0006_alter_films_imagename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='imageName',
            field=models.FileField(upload_to='./static'),
        ),
    ]
