# Generated by Django 4.2.5 on 2023-10-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Films', '0007_alter_films_imagename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='imageName',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
