# Generated by Django 4.2.5 on 2023-10-07 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Realisateur', '0001_initial'),
        ('Films', '0011_alter_films_imagename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='imageName',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='films',
            name='realisateur_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='films', to='Realisateur.realisateur'),
        ),
        migrations.DeleteModel(
            name='Realisateur',
        ),
    ]
