# Generated by Django 4.2.5 on 2023-10-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Films', '0012_alter_films_imagename_alter_films_realisateur_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='imageName',
            field=models.ImageField(upload_to='Films'),
        ),
    ]
