# Generated by Django 4.2.5 on 2023-10-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acteurs', '0001_initial'),
        ('Films', '0013_alter_films_imagename'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='acteurs',
            field=models.ManyToManyField(to='Acteurs.acteur'),
        ),
    ]
